name: CI

on: 
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test
